name: flutter_sample
description: A Flutter example app by najeira.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^0.7.2
  state_notifier: ^0.6.0
  rxdart: ^0.23.1
  get_it: ^3.1.0
  freezed_annotation: 
  json_annotation: ^3.0.1
  http: ^0.12.0+4
  intl: ^0.16.1
  hive: ^1.3.0
  hive_flutter: ^0.3.0+1
  like_button: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^3.2.5
  build_runner: ^1.7.3
  freezed: 

flutter:
  uses-material-design: true
