name: flutter_sample
description: A Flutter example app by najeira.

version: 1.0.0+1

environment:
  sdk: ">=2.5.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.8
  provider: ^4.0.2
  rxdart: ^0.23.1
  store_builder: ^0.3.1
  bloc: ^3.0.0
  flutter_bloc: ^3.1.0
  get_it: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
