name: flutter_sample
description: A Flutter example app by najeira.

version: 1.0.0+1

environment:
  sdk: ">=2.5.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.0.4
  rxdart: ^0.23.1
  get_it: ^3.1.0
  json_annotation: ^3.0.1
  http: ^0.12.0+4
  intl: ^0.16.1
  hive: ^1.3.0
  hive_flutter: ^0.3.0+1
  like_button: ^0.2.0
  store_builder:
    path: ../flutter-store-builder
  notification_handler:
    path: ../flutter-notification-handler

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^3.2.5
  build_runner: ^1.7.3

flutter:
  uses-material-design: true
