name: flutter_sample
description: A Flutter example app by najeira.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^0.11.1
  state_notifier: ^0.6.0
  get_it: ^5.0.1
  freezed_annotation: 
  json_annotation: ^3.0.1
  http: ^0.12.2
  intl: ^0.16.1
  hive: ^1.4.4
  hive_flutter: ^0.3.1
  like_button: ^0.2.0
  url_launcher: ^5.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^3.5.0
  build_runner: 
  freezed: 

flutter:
  uses-material-design: true
